version: "3.9"

services:
  sa_frontend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8181:80"
    networks:
      - sa_shared
      - default
    restart: always

networks:
  default:
  sa_shared:
    external: true